// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageTest.proto

#include "MessageTest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class MsgTestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgTest>
      _instance;
} _MsgTest_default_instance_;
namespace protobuf_MessageTest_2eproto {
static void InitDefaultsMsgTest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_MsgTest_default_instance_;
    new (ptr) ::MsgTest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MsgTest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MsgTest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMsgTest}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MsgTest.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MsgTest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MsgTest, inttest_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MsgTest, uinttest_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MsgTest, bytestest_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MsgTest, stringtest_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MsgTest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_MsgTest_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "MessageTest.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021MessageTest.proto\"S\n\007MsgTest\022\017\n\007intTes"
      "t\030\001 \001(\005\022\020\n\010uintTest\030\002 \001(\r\022\021\n\tbytesTest\030\003"
      " \001(\014\022\022\n\nstringTest\030\004 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 112);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageTest.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MessageTest_2eproto

// ===================================================================

void MsgTest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgTest::kIntTestFieldNumber;
const int MsgTest::kUintTestFieldNumber;
const int MsgTest::kBytesTestFieldNumber;
const int MsgTest::kStringTestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgTest::MsgTest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MessageTest_2eproto::scc_info_MsgTest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MsgTest)
}
MsgTest::MsgTest(const MsgTest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bytestest_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bytestest().size() > 0) {
    bytestest_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytestest_);
  }
  stringtest_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringtest().size() > 0) {
    stringtest_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringtest_);
  }
  ::memcpy(&inttest_, &from.inttest_,
    static_cast<size_t>(reinterpret_cast<char*>(&uinttest_) -
    reinterpret_cast<char*>(&inttest_)) + sizeof(uinttest_));
  // @@protoc_insertion_point(copy_constructor:MsgTest)
}

void MsgTest::SharedCtor() {
  bytestest_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stringtest_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&inttest_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&uinttest_) -
      reinterpret_cast<char*>(&inttest_)) + sizeof(uinttest_));
}

MsgTest::~MsgTest() {
  // @@protoc_insertion_point(destructor:MsgTest)
  SharedDtor();
}

void MsgTest::SharedDtor() {
  bytestest_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stringtest_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MsgTest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MsgTest::descriptor() {
  ::protobuf_MessageTest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MessageTest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgTest& MsgTest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MessageTest_2eproto::scc_info_MsgTest.base);
  return *internal_default_instance();
}


void MsgTest::Clear() {
// @@protoc_insertion_point(message_clear_start:MsgTest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bytestest_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stringtest_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&inttest_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&uinttest_) -
      reinterpret_cast<char*>(&inttest_)) + sizeof(uinttest_));
  _internal_metadata_.Clear();
}

bool MsgTest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MsgTest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 intTest = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &inttest_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 uintTest = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uinttest_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bytesTest = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytestest()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stringTest = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringtest()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringtest().data(), static_cast<int>(this->stringtest().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MsgTest.stringTest"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MsgTest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MsgTest)
  return false;
#undef DO_
}

void MsgTest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MsgTest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 intTest = 1;
  if (this->inttest() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->inttest(), output);
  }

  // uint32 uintTest = 2;
  if (this->uinttest() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->uinttest(), output);
  }

  // bytes bytesTest = 3;
  if (this->bytestest().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->bytestest(), output);
  }

  // string stringTest = 4;
  if (this->stringtest().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringtest().data(), static_cast<int>(this->stringtest().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MsgTest.stringTest");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->stringtest(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MsgTest)
}

::google::protobuf::uint8* MsgTest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MsgTest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 intTest = 1;
  if (this->inttest() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->inttest(), target);
  }

  // uint32 uintTest = 2;
  if (this->uinttest() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->uinttest(), target);
  }

  // bytes bytesTest = 3;
  if (this->bytestest().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->bytestest(), target);
  }

  // string stringTest = 4;
  if (this->stringtest().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringtest().data(), static_cast<int>(this->stringtest().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MsgTest.stringTest");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->stringtest(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgTest)
  return target;
}

size_t MsgTest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MsgTest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes bytesTest = 3;
  if (this->bytestest().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bytestest());
  }

  // string stringTest = 4;
  if (this->stringtest().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringtest());
  }

  // int32 intTest = 1;
  if (this->inttest() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->inttest());
  }

  // uint32 uintTest = 2;
  if (this->uinttest() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->uinttest());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MsgTest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MsgTest)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgTest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgTest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MsgTest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MsgTest)
    MergeFrom(*source);
  }
}

void MsgTest::MergeFrom(const MsgTest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MsgTest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bytestest().size() > 0) {

    bytestest_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytestest_);
  }
  if (from.stringtest().size() > 0) {

    stringtest_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringtest_);
  }
  if (from.inttest() != 0) {
    set_inttest(from.inttest());
  }
  if (from.uinttest() != 0) {
    set_uinttest(from.uinttest());
  }
}

void MsgTest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MsgTest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgTest::CopyFrom(const MsgTest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MsgTest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgTest::IsInitialized() const {
  return true;
}

void MsgTest::Swap(MsgTest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgTest::InternalSwap(MsgTest* other) {
  using std::swap;
  bytestest_.Swap(&other->bytestest_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  stringtest_.Swap(&other->stringtest_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(inttest_, other->inttest_);
  swap(uinttest_, other->uinttest_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MsgTest::GetMetadata() const {
  protobuf_MessageTest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MessageTest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MsgTest* Arena::CreateMaybeMessage< ::MsgTest >(Arena* arena) {
  return Arena::CreateInternal< ::MsgTest >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
